### PR TITLE
Shows file selected

### PR DESCRIPTION
**Pull request by wilswu**
The spacing's off but I don't know how to fix it

### CODE REVIEW

**Comment by Guad** [comment]
It only shows the first file selected. I think this is unnecessary though.

**Comment by Luminarys** [comment]
I don't think showing the filename is necessary, but it would be nice to provide a visual indication of whether or not a user has selected a file(s). Some slight visual cue such as a border or button color change would be nice.

**Comment by Guad** [comment]
Maybe change the upload button color from grayscale to colorful when something is selected?

**Comment by Luminarys** [comment]
Or make the font color yellow or something in the submit/upload buttons.

**Comment by Guad** [comment]
Added in d50268c9395d835e2e5aa671eacc21a612a894c1, what do you think?

**Comment by Luminarys** [comment]
Looks good, but one thing is that after an upload have the selected file be cleared. Right now it persists, even through a page reload.

**Comment by Guad** [comment]
Done, though it empties after every upload has been completed.

**Comment by wilswu** [comment]
I still think that it would be nice if the user had verification that they selected the file they wanted to.
Most major sites (4chan, imgur) show file selected.

**Comment by Luminarys** [comment]
I think it would be nice too, but the issue is that you can select multiple files and stuff starts to get messy at that point. Perhaps have it display file name if there's one file and "multiple files" if there's more than one?

**Comment by Guad** [comment]
"multiple files" is too ambiguous, might as well not display anything at all.

**Comment by wilswu** [comment]
I added the showing of multiple files.

**Comment by Luminarys** [comment]
We need a way to do CI for this, so that we can see what your alterations actually look like. Can you send a screencap or something?

**Comment by Guad** [comment]
That still only shows the first file selected, not all of them

**Comment by Guad** [comment]
@Luminarys Use whatever CI service you wish. Also your current fuwa.se deployment seems to be behind, it has a bug where files >10mib won't get uploaded.

**Comment by Luminarys** [comment]
Yea, that's cloudflare. I've updated the server and have tested the most recent updates by enabling development mode, but we have to wait an hour or two for its cache to reupdate with the new files.

**Comment by wilswu** [comment]
fuwa

Multiple files work on my end

**Comment by Luminarys** [comment]
This doesn't look too bad, and I assume the names will wrap around. Thoughts @Guad?

**Comment by Guad** [comment]
Just tested it. Doesn't work as intended: when you change, old text doesn't disappear, and with multiple selection only displays the first one.
[I made a webm: https://fuwa.se/rxiv5.webm/test.webm](https://fuwa.se/rxiv5.webm/test.webm)

**Comment by Luminarys** [comment]
I mean this could be pretty easily fixed by having jquery clear that element whenever there's a reselection, right?

**Comment by Guad** [comment]
Yeah, but how I would do it is on change make a file card, then update it on upload. Though this is more complicated.

**Comment by Luminarys** [comment]
Yea that does sound like a slightly more elegant way of doing it. The code is already in place for the cards, it's just the ajax request needs to trigger on upload. That and reselection needs to be properly handled.

**Comment by Guad** [comment]
Also this would fix it

```
function showFiles(){
    fileDisplay.style.display="block";
    fileDisplay.textContent = 'Files Selected: ';
    for (var i = 0; i < document.getElementById('files').files.length; i++) {
        fileDisplay.textContent += document.getElementById('files').files[i].name + " ";
    }
}
```

**Comment by Guad** [comment]
@Luminarys I'll try to implement this

**Comment by Luminarys** [comment]
Ok cool.

**Pull request closed without merging**
