### PR TITLE
Added file cards for selected files

### PR DESCRIPTION
**Pull request by Guad**
What do you think?

### CODE REVIEW

**Comment by Luminarys** [comment]
Can you merge it so I can do some testing?

**Comment by Guad** [comment]
Not yet, I just found a bug, I'll merge it when I fix it.

**Comment by Luminarys** [comment]
Alright sure.

**Comment by Guad** [comment]
Merging

**Comment by Luminarys** [comment]
Looks good, but there seem to be a few issues that seem to arise when you play with concurrently switching files and uploads. The select files and upload buttons could be locked while files are being uploaded to prevent this glitchiness, or some substantial bug testing could be done.

**Comment by Guad** [comment]
Yeah, I'll try to fix it. If I give up I'll just lock the upload button.

**Comment by Luminarys** [comment]
You'll want to lock both upload and select files, just playing around with select files, I ended up with this: https://fuwa.se/qlbhs.png

**Comment by Guad** [comment]
Both buttons should lock now

**Pull request merged**
